#file to adjust the appearance of the webpage (keep an eye on the piechart, that the backgrounds match and the text is readable)
[theme]
base="dark"
backgroundColor="#0F1116"
secondaryBackgroundColor="#262730"
textColor="#FFFFFF"
font="sans serif"
